[build]
builder = "NIXPACKS"

[deploy]
startCommand = "gunicorn --config gunicorn.conf.py app:app"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[deploy.env]
PYTHONUNBUFFERED = "1"